### ISSUE TITLE
emtpy epub

### ISSUE THREAD

**Issue by suppenkaspar109** [vlaborie/reMarkable-sync#1]
Hey, 
thanks for creating this piece of software.
I just wanted to test it, but unfortunatly failed. Problem is that are downloaded epub files from wallabag are empty. 
I can see all name, but there is no content.
Any idea, what could be wrong?

**Comment by TheOnAndOnlyZenomat** [comment]
Disclaimer: I am not the maintainer.
I took a look into this, because I also want this thing to work, and I think it has something to do with the .content files being wonky. 
The ebooks get written correctly, but the .content files don't specify correct sizes and pageCounts as well as pages.

Take all this with a grain of salt, because I only looked into this for maybe half an hours and don't know anything about how remarkable handles storing books.
I will look further into it, tho I can't guarantee to get it to work and help is appreciated.

**Comment by TheOnAndOnlyZenomat** [comment]
I found the solution to this problem.
I was half right with the .content files. The only thing we had to to was create one for every entry and add a `{}` to it, before we restart xochitl.
It takes a bit for the remarkable to create new content files for all entries, because it has to index them, create previews and stuff, so in my experience it is a bit slow (time increasing with the amount of entries), but it works.
I'll create a PR, which you can then apply to your code and resync the compiled binary to the remarkable.

**Comment by vlaborie** [comment]
Hello,

Thank's for your interest !

This issue was patched on Gitlab, see https://github.com/vlaborie/remarkable-sync/pull/2 for details.
